import type { Station } from '../types/station'

export const fallbackStations: Station[] = [
  {
    stationuuid: 'fallback-jazz-nl',
    name: 'Jazz NL',
    country: 'Netherlands',
    state: '',
    favicon: '',
    url_resolved: 'https://stream.example/fallback-jazz',
    language: 'dutch',
    tags: 'jazz,news',
    votes: 12,
    clickcount: 42,
    lastcheckok: 1,
    geo_lat: 52.37,
    geo_long: 4.9,
  },
  {
    stationuuid: 'fallback-pop-be',
    name: 'Pop BE',
    country: 'Belgium',
    state: '',
    favicon: '',
    url_resolved: 'https://stream.example/fallback-pop',
    language: 'french',
    tags: 'pop',
    votes: 8,
    clickcount: 31,
    lastcheckok: 1,
    geo_lat: 50.85,
    geo_long: 4.35,
  },
  {
    stationuuid: 'fallback-talk-us',
    name: 'Talk US',
    country: 'United States',
    state: '',
    favicon: '',
    url_resolved: 'https://stream.example/fallback-talk',
    language: 'english',
    tags: 'talk',
    votes: 5,
    clickcount: 19,
    lastcheckok: 1,
    geo_lat: null,
    geo_long: null,
  },
]
